version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor 